version: '3.9'

x-gpu-config:
  &gpu-config
  # restart: always
  env_file:
    - .env
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

services:
  # Model provider
  ollama: 
    <<: *gpu-config
    image: ollama/ollama:${MODEL_STACK_VERSION}
    container_name: ollama
    ports:
      - ${OLLAMA_PORT}:11434
    volumes:
      - ollama:/root/.ollama
    pull_policy: always
    tty: true

  # Custom RAG processing
  pipelines:
    <<: *gpu-config
    build:
      context: ./pipelines
      dockerfile: Dockerfile
      args:
        USE_CUDA: "true"
        USE_CUDA_VER: "cu121"
    image: custom_build_pipelines
    container_name: pipelines
    ports:
      - ${PIPELINE_PORT}:9099
    env_file:
      - .env
    volumes:
      - ./pipelines-RAG/:/app/pipelines/
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - ollama
  
  # Frontend
  open-webui:
    <<: *gpu-config
    image: ghcr.io/open-webui/open-webui:${OPEN_WEBUI_STACK_VERSION}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
      - ./app/document/:/app/backend/data/docs
    ports:
      - ${OPEN_WEBUI_PORT}:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - ollama
      - pipelines
  
  # text-embeddings-inference
  text-embeddings-inference:
    <<: *gpu-config
    image: ghcr.io/huggingface/text-embeddings-inference:1.5
    container_name: text-embeddings-inference
    ports:
      - 8080:80
    volumes:
      - embedding-inference:/data
    pull_policy: always

volumes:
  ollama:
    name: ${COMPOSE_PROJECT_NAME}-ollama
  embedding-inference:
    name: ${COMPOSE_PROJECT_NAME}-embedding-inference
  open-webui:
    name: ${COMPOSE_PROJECT_NAME}-open-webui