version: '3.9'

x-gpu-config:
  &gpu-config
  restart: unless-stopped
  environment:
    - TZ=Asia/Bangkok
  env_file:
    - .env
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

services:
  jupyter:
    container_name: jupyter
    build: ./app
    restart: unless-stopped
    volumes:
      - ./app/:/opt/app/
    environment:
      - TZ=Asia/Bangkok
    env_file:
      - .env
    ports:
      - ${JUPYTER_PORT}:8888
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--no-browser", "--allow-root", "--NotebookApp.token=''", "--NotebookApp.password=''"]
  
  ollama:
    <<: *gpu-config
    image: ollama/ollama:latest
    container_name: ollama
    expose:
      - ${OLLAMA_PORT}
    volumes:
      - ollama:/root/.ollama
    pull_policy: always
    tty: true
  
  open-webui:
    <<: *gpu-config
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
      - ./app/document/:/app/backend/data/docs
    ports:
      - ${OPEN_WEBUI_PORT}:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - ollama

volumes:
  ollama:
    name: ${COMPOSE_PROJECT_NAME}-ollama
  open-webui:
    name: ${COMPOSE_PROJECT_NAME}-open-webui