version: '3.9'

x-gpu-config:
  &gpu-config
  restart: unless-stopped
  env_file:
    - .env
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

services:
  # Model provider
  ollama: 
    <<: *gpu-config
    image: ollama/ollama:${MODEL_STACK_VERSION}
    container_name: ollama
    expose:
      - ${OLLAMA_PORT}
    volumes:
      - ollama:/root/.ollama
    pull_policy: always
    tty: true

  # Custom RAG processing
  pipelines:
    <<: *gpu-config
    build:
      context: ./pipelines
      dockerfile: Dockerfile
    container_name: pipelines
    ports:
      - ${PIPELINE_PORT}:9099
    env_file:
      - .env
    volumes:
      - ./pipelines/python_script/:/app/pipelines/pipelines/
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: always
    command: /bin/bash -c "./start.sh"
  
  # Frontend
  open-webui:
    <<: *gpu-config
    image: ghcr.io/open-webui/open-webui:${OPEN_WEBUI_STACK_VERSION}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
      - ./app/document/:/app/backend/data/docs
    ports:
      - ${OPEN_WEBUI_PORT}:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - ollama
      - pipelines

  # jupyter:
  #   container_name: jupyter
  #   build: ./app
  #   restart: unless-stopped
  #   volumes:
  #     - ./app/:/opt/app/
  #   environment:
  #     - TZ=Asia/Bangkok
  #   env_file:
  #     - .env
  #   ports:
  #     - ${JUPYTER_PORT}:8888

volumes:
  ollama:
    name: ${COMPOSE_PROJECT_NAME}-ollama
  open-webui:
    name: ${COMPOSE_PROJECT_NAME}-open-webui